# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d74c328f74c147f3e8f587237a6d85cd29c73eeb1d4139b36e258bcceeaee028858829f32be35e0859e510220a90723f145266dc450397a763f06cbfb86c9f8f
  google_api_key: '17226504534-46j7v185ncs1af1l3r4s1ju1nlp5qa22.apps.googleusercontent.com'
  google_api_secret: 'lClY6AT8zA_KE1JDr4sOdsop'
  google_application_name: 'Attachments IO'
  google_application_version: '1.0.0'

test:
  secret_key_base: d74c328f74c147f3e8f587237a6d85cd29c73eeb1d4139b36e258bcceeaee028858829f32be35e0859e510220a90723f145266dc450397a763f06cbfb86c9f8f
  google_api_key: '17226504534-46j7v185ncs1af1l3r4s1ju1nlp5qa22.apps.googleusercontent.com'
  google_api_secret: 'lClY6AT8zA_KE1JDr4sOdsop'
  google_application_name: 'Attachments IO'
  google_application_version: '1.0.0'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || 'd74c328f74c147f3e8f587237a6d85cd29c73eeb1d4139b36e258bcceeaee028858829f32be35e0859e510220a90723f145266dc450397a763f06cbfb86c9f8f' %>
  google_api_key: '17226504534-46j7v185ncs1af1l3r4s1ju1nlp5qa22.apps.googleusercontent.com'
  google_api_secret: 'lClY6AT8zA_KE1JDr4sOdsop'
  google_application_name: 'Attachments IO'
  google_application_version: '1.0.0'